using Newtonsoft.Json;
using Serilog;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Tab;

namespace InstagramCreator.OtpServices.CountryHelper
{
    public class CountryCodeHelper
    {

        public class CountryService
        {
            public string Country { get; set; }
            public string Sim5 { get; set; }
            public string GetSmsCode { get; set; }
            public string Sms365{ get; set; }
        }
        public static string Contries = @"[{
      ""Country"":""Afghanistan"",
      ""Sim5"":""afghanistan"",
      ""getsmscode"":""74"",
      ""Sms365"":""74""
   },
   {
      ""Country"":""Albania"",
      ""Sim5"":""albania"",
      ""getsmscode"":""155"",
      ""Sms365"":""155""
   },
   {
      ""Country"":""Algeria"",
      ""Sim5"":""algeria"",
      ""getsmscode"":""58"",
      ""Sms365"":""58""
   },
   {
      ""Country"":""Angola"",
      ""Sim5"":""angola"",
      ""getsmscode"":""76"",
      ""Sms365"":""76""
   },
   {
      ""Country"":""Anguilla"",
      ""Sim5"":""anguilla"",
      ""getsmscode"":""181"",
      ""Sms365"":""181""
   },
   {
      ""Country"":""Antigua and Barbuda"",
      ""Sim5"":""antiguaandbarbuda"",
      ""getsmscode"":""169"",
      ""Sms365"":""169""
   },
   {
      ""Country"":""Argentina"",
      ""Sim5"":""argentina"",
      ""getsmscode"":""39"",
      ""Sms365"":""39""
   },
   {
      ""Country"":""Armenia"",
      ""Sim5"":""armenia"",
      ""getsmscode"":""148"",
      ""Sms365"":""148""
   },
   {
      ""Country"":""Aruba"",
      ""Sim5"":""aruba"",
      ""getsmscode"":""179"",
      ""Sms365"":""179""
   },
   {
      ""Country"":""Australia"",
      ""Sim5"":""australia"",
      ""getsmscode"":""175"",
      ""Sms365"":""175""
   },
   {
      ""Country"":""Austria"",
      ""Sim5"":""austria"",
      ""getsmscode"":""50"",
      ""Sms365"":""50""
   },
   {
      ""Country"":""Azerbaijan"",
      ""Sim5"":""azerbaijan"",
      ""getsmscode"":""35"",
      ""Sms365"":""35""
   },
   {
      ""Country"":""Bahamas"",
      ""Sim5"":""bahamas"",
      ""getsmscode"":""122"",
      ""Sms365"":""122""
   },
   {
      ""Country"":""Bahrain"",
      ""Sim5"":""bahrain"",
      ""getsmscode"":""145"",
      ""Sms365"":""145""
   },
   {
      ""Country"":""Bangladesh"",
      ""Sim5"":""bangladesh"",
      ""getsmscode"":""60"",
      ""Sms365"":""60""
   },
   {
      ""Country"":""Barbados"",
      ""Sim5"":""barbados"",
      ""getsmscode"":""118"",
      ""Sms365"":""118""
   },
   {
      ""Country"":""Belarus"",
      ""Sim5"":""belarus"",
      ""getsmscode"":""51"",
      ""Sms365"":""51""
   },
   {
      ""Country"":""Belgium"",
      ""Sim5"":""belgium"",
      ""getsmscode"":""82"",
      ""Sms365"":""82""
   },
   {
      ""Country"":""Belize"",
      ""Sim5"":""belize"",
      ""getsmscode"":""124"",
      ""Sms365"":""124""
   },
   {
      ""Country"":""Benin"",
      ""Sim5"":""benin"",
      ""getsmscode"":""120"",
      ""Sms365"":""120""
   },
   {
      ""Country"":""Bhutan"",
      ""Sim5"":""bhutane"",
      ""getsmscode"":""158"",
      ""Sms365"":""158""
   },
   {
      ""Country"":""Bosnia and Herzegovina"",
      ""Sim5"":""bih"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Bolivia"",
      ""Sim5"":""bolivia"",
      ""getsmscode"":""92"",
      ""Sms365"":""92""
   },
   {
      ""Country"":""Botswana"",
      ""Sim5"":""botswana"",
      ""getsmscode"":""123"",
      ""Sms365"":""123""
   },
   {
      ""Country"":""Brazil"",
      ""Sim5"":""brazil"",
      ""getsmscode"":""73"",
      ""Sms365"":""73""
   },
   {
      ""Country"":""Bulgaria"",
      ""Sim5"":""bulgaria"",
      ""getsmscode"":""83"",
      ""Sms365"":""83""
   },
   {
      ""Country"":""Burkina Faso"",
      ""Sim5"":""burkinafaso"",
      ""getsmscode"":""152"",
      ""Sms365"":""152""
   },
   {
      ""Country"":""Burundi"",
      ""Sim5"":""burundi"",
      ""getsmscode"":""119"",
      ""Sms365"":""119""
   },
   {
      ""Country"":""Cambodia"",
      ""Sim5"":""cambodia"",
      ""getsmscode"":""24"",
      ""Sms365"":""24""
   },
   {
      ""Country"":""Cameroon"",
      ""Sim5"":""cameroon"",
      ""getsmscode"":""41"",
      ""Sms365"":""41""
   },
   {
      ""Country"":""Canada"",
      ""Sim5"":""canada"",
      ""getsmscode"":""36"",
      ""Sms365"":""36""
   },
   {
      ""Country"":""Cape Verde"",
      ""Sim5"":""capeverde"",
      ""getsmscode"":""186"",
      ""Sms365"":""186""
   },
   {
      ""Country"":""Cayman Islands"",
      ""Sim5"":""caymanislands"",
      ""getsmscode"":""170"",
      ""Sms365"":""170""
   },
   {
      ""Country"":""Chad"",
      ""Sim5"":""chad"",
      ""getsmscode"":""42"",
      ""Sms365"":""42""
   },
   {
      ""Country"":""Chile"",
      ""Sim5"":""chile"",
      ""getsmscode"":""151"",
      ""Sms365"":""151""
   },
   {
      ""Country"":""China"",
      ""Sim5"":""china"",
      ""getsmscode"":""3"",
      ""Sms365"":""3""
   },
   {
      ""Country"":""Colombia"",
      ""Sim5"":""colombia"",
      ""getsmscode"":""33"",
      ""Sms365"":""33""
   },
   {
      ""Country"":""Comoros"",
      ""Sim5"":""comoros"",
      ""getsmscode"":""133"",
      ""Sms365"":""133""
   },
   {
      ""Country"":""Congo"",
      ""Sim5"":""congo"",
      ""getsmscode"":""150"",
      ""Sms365"":""150""
   },
   {
      ""Country"":""Costa Rica"",
      ""Sim5"":""costarica"",
      ""getsmscode"":""93"",
      ""Sms365"":""93""
   },
   {
      ""Country"":""Croatia"",
      ""Sim5"":""croatia"",
      ""getsmscode"":""45"",
      ""Sms365"":""45""
   },
   {
      ""Country"":""Cuba"",
      ""Sim5"":""cuba"",
      ""getsmscode"":""113"",
      ""Sms365"":""113""
   },
   {
      ""Country"":""Cyprus"",
      ""Sim5"":""cyprus"",
      ""getsmscode"":""77"",
      ""Sms365"":""77""
   },
   {
      ""Country"":""Czechia"",
      ""Sim5"":""czech"",
      ""getsmscode"":""63"",
      ""Sms365"":""63""
   },
   {
      ""Country"":""Denmark"",
      ""Sim5"":""denmark"",
      ""getsmscode"":""172"",
      ""Sms365"":""172""
   },
   {
      ""Country"":""Djibouti"",
      ""Sim5"":""djibouti"",
      ""getsmscode"":""168"",
      ""Sms365"":""168""
   },
   {
      ""Country"":""Dominica"",
      ""Sim5"":""dominica"",
      ""getsmscode"":""126"",
      ""Sms365"":""126""
   },
   {
      ""Country"":""Dominican Republic"",
      ""Sim5"":""dominicana"",
      ""getsmscode"":""109"",
      ""Sms365"":""109""
   },
   {
      ""Country"":""Drcongo"",
      ""Sim5"":""drcongo"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""East Timor"",
      ""Sim5"":""easttimor"",
      ""getsmscode"":""91"",
      ""Sms365"":""91""
   },
   {
      ""Country"":""Ecuador"",
      ""Sim5"":""ecuador"",
      ""getsmscode"":""105"",
      ""Sms365"":""105""
   },
   {
      ""Country"":""Egypt"",
      ""Sim5"":""egypt"",
      ""getsmscode"":""21"",
      ""Sms365"":""21""
   },
   {
      ""Country"":""England"",
      ""Sim5"":""england"",
      ""getsmscode"":""16"",
      ""Sms365"":""16""
   },
   {
      ""Country"":""Equatorial Guinea"",
      ""Sim5"":""equatorialguinea"",
      ""getsmscode"":""167"",
      ""Sms365"":""167""
   },
   {
      ""Country"":""Eritrea"",
      ""Sim5"":""eritrea"",
      ""getsmscode"":""176"",
      ""Sms365"":""176""
   },
   {
      ""Country"":""Estonia"",
      ""Sim5"":""estonia"",
      ""getsmscode"":""34"",
      ""Sms365"":""34""
   },
   {
      ""Country"":""Ethiopia"",
      ""Sim5"":""ethiopia"",
      ""getsmscode"":""71"",
      ""Sms365"":""71""
   },
   {
      ""Country"":""Finland"",
      ""Sim5"":""finland"",
      ""getsmscode"":""163"",
      ""Sms365"":""163""
   },
   {
      ""Country"":""France"",
      ""Sim5"":""france"",
      ""getsmscode"":""78"",
      ""Sms365"":""78""
   },
   {
      ""Country"":""French Guiana"",
      ""Sim5"":""frenchguiana"",
      ""getsmscode"":""162"",
      ""Sms365"":""162""
   },
   {
      ""Country"":""Gabon"",
      ""Sim5"":""gabon"",
      ""getsmscode"":""154"",
      ""Sms365"":""154""
   },
   {
      ""Country"":""Gambia"",
      ""Sim5"":""gambia"",
      ""getsmscode"":""28"",
      ""Sms365"":""28""
   },
   {
      ""Country"":""Georgia"",
      ""Sim5"":""georgia"",
      ""getsmscode"":""128"",
      ""Sms365"":""128""
   },
   {
      ""Country"":""Germany"",
      ""Sim5"":""germany"",
      ""getsmscode"":""43"",
      ""Sms365"":""43""
   },
   {
      ""Country"":""Ghana"",
      ""Sim5"":""ghana"",
      ""getsmscode"":""38"",
      ""Sms365"":""38""
   },
   {
      ""Country"":""Greece"",
      ""Sim5"":""greece"",
      ""getsmscode"":""129"",
      ""Sms365"":""129""
   },
   {
      ""Country"":""Grenada"",
      ""Sim5"":""grenada"",
      ""getsmscode"":""127"",
      ""Sms365"":""127""
   },
   {
      ""Country"":""Guadeloupe"",
      ""Sim5"":""guadeloupe"",
      ""getsmscode"":""160"",
      ""Sms365"":""160""
   },
   {
      ""Country"":""Guatemala"",
      ""Sim5"":""guatemala"",
      ""getsmscode"":""94"",
      ""Sms365"":""94""
   },
   {
      ""Country"":""Guinea"",
      ""Sim5"":""guinea"",
      ""getsmscode"":""68"",
      ""Sms365"":""68""
   },
   {
      ""Country"":""Guinea-Bissau"",
      ""Sim5"":""guineabissau"",
      ""getsmscode"":""130"",
      ""Sms365"":""130""
   },
   {
      ""Country"":""Guyana"",
      ""Sim5"":""guyana"",
      ""getsmscode"":""131"",
      ""Sms365"":""131""
   },
   {
      ""Country"":""Haiti"",
      ""Sim5"":""haiti"",
      ""getsmscode"":""26"",
      ""Sms365"":""26""
   },
   {
      ""Country"":""Honduras"",
      ""Sim5"":""honduras"",
      ""getsmscode"":""88"",
      ""Sms365"":""88""
   },
   {
      ""Country"":""Hong Kong"",
      ""Sim5"":""hongkong"",
      ""getsmscode"":""14"",
      ""Sms365"":""14""
   },
   {
      ""Country"":""Hungary"",
      ""Sim5"":""hungary"",
      ""getsmscode"":""84"",
      ""Sms365"":""84""
   },
   {
      ""Country"":""India"",
      ""Sim5"":""india"",
      ""getsmscode"":""22"",
      ""Sms365"":""22""
   },
   {
      ""Country"":""Indonesia"",
      ""Sim5"":""indonesia"",
      ""getsmscode"":""6"",
      ""Sms365"":""6""
   },
   {
      ""Country"":""Iran"",
      ""Sim5"":""iran"",
      ""getsmscode"":""57"",
      ""Sms365"":""57""
   },
   {
      ""Country"":""Iraq"",
      ""Sim5"":""iraq"",
      ""getsmscode"":""47"",
      ""Sms365"":""47""
   },
   {
      ""Country"":""Ireland"",
      ""Sim5"":""ireland"",
      ""getsmscode"":""23"",
      ""Sms365"":""23""
   },
   {
      ""Country"":""Israel"",
      ""Sim5"":""israel"",
      ""getsmscode"":""13"",
      ""Sms365"":""13""
   },
   {
      ""Country"":""Italy"",
      ""Sim5"":""italy"",
      ""getsmscode"":""86"",
      ""Sms365"":""86""
   },
   {
      ""Country"":""Ivory Coast"",
      ""Sim5"":""ivorycoast"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Jamaica"",
      ""Sim5"":""jamaica"",
      ""getsmscode"":""103"",
      ""Sms365"":""103""
   },
   {
      ""Country"":""Japan"",
      ""Sim5"":""japan"",
      ""getsmscode"":""182"",
      ""Sms365"":""182""
   },
   {
      ""Country"":""Jordan"",
      ""Sim5"":""jordan"",
      ""getsmscode"":""116"",
      ""Sms365"":""116""
   },
   {
      ""Country"":""Kazakhstan"",
      ""Sim5"":""kazakhstan"",
      ""getsmscode"":""2"",
      ""Sms365"":""2""
   },
   {
      ""Country"":""Kenya"",
      ""Sim5"":""kenya"",
      ""getsmscode"":""8"",
      ""Sms365"":""8""
   },
   {
      ""Country"":""Kuwait"",
      ""Sim5"":""kuwait"",
      ""getsmscode"":""100"",
      ""Sms365"":""100""
   },
   {
      ""Country"":""Kyrgyzstan"",
      ""Sim5"":""kyrgyzstan"",
      ""getsmscode"":""11"",
      ""Sms365"":""11""
   },
   {
      ""Country"":""Laos"",
      ""Sim5"":""laos"",
      ""getsmscode"":""25"",
      ""Sms365"":""25""
   },
   {
      ""Country"":""Latvia"",
      ""Sim5"":""latvia"",
      ""getsmscode"":""49"",
      ""Sms365"":""49""
   },
   {
      ""Country"":""Lesotho"",
      ""Sim5"":""lesotho"",
      ""getsmscode"":""136"",
      ""Sms365"":""136""
   },
   {
      ""Country"":""Liberia"",
      ""Sim5"":""liberia"",
      ""getsmscode"":""135"",
      ""Sms365"":""135""
   },
   {
      ""Country"":""Libya"",
      ""Sim5"":""libya"",
      ""getsmscode"":""102"",
      ""Sms365"":""102""
   },
   {
      ""Country"":""Lithuania"",
      ""Sim5"":""lithuania"",
      ""getsmscode"":""44"",
      ""Sms365"":""44""
   },
   {
      ""Country"":""Luxembourg"",
      ""Sim5"":""luxembourg"",
      ""getsmscode"":""165"",
      ""Sms365"":""165""
   },
   {
      ""Country"":""Macau"",
      ""Sim5"":""macau"",
      ""getsmscode"":""20"",
      ""Sms365"":""20""
   },
   {
      ""Country"":""Madagascar"",
      ""Sim5"":""madagascar"",
      ""getsmscode"":""17"",
      ""Sms365"":""17""
   },
   {
      ""Country"":""Malawi"",
      ""Sim5"":""malawi"",
      ""getsmscode"":""137"",
      ""Sms365"":""137""
   },
   {
      ""Country"":""Malaysia"",
      ""Sim5"":""malaysia"",
      ""getsmscode"":""7"",
      ""Sms365"":""7""
   },
   {
      ""Country"":""Maldives"",
      ""Sim5"":""maldives"",
      ""getsmscode"":""159"",
      ""Sms365"":""159""
   },
   {
      ""Country"":""Mali"",
      ""Sim5"":""mali"",
      ""getsmscode"":""69"",
      ""Sms365"":""69""
   },
   {
      ""Country"":""Mauritania"",
      ""Sim5"":""mauritania"",
      ""getsmscode"":""114"",
      ""Sms365"":""114""
   },
   {
      ""Country"":""Mauritius"",
      ""Sim5"":""mauritius"",
      ""getsmscode"":""157"",
      ""Sms365"":""157""
   },
   {
      ""Country"":""Mexico"",
      ""Sim5"":""mexico"",
      ""getsmscode"":""54"",
      ""Sms365"":""54""
   },
   {
      ""Country"":""Moldova"",
      ""Sim5"":""moldova"",
      ""getsmscode"":""85"",
      ""Sms365"":""85""
   },
   {
      ""Country"":""Mongolia"",
      ""Sim5"":""mongolia"",
      ""getsmscode"":""72"",
      ""Sms365"":""72""
   },
   {
      ""Country"":""Montenegro"",
      ""Sim5"":""montenegro"",
      ""getsmscode"":""171"",
      ""Sms365"":""171""
   },
   {
      ""Country"":""Montserrat"",
      ""Sim5"":""montserrat"",
      ""getsmscode"":""180"",
      ""Sms365"":""180""
   },
   {
      ""Country"":""Morocco"",
      ""Sim5"":""morocco"",
      ""getsmscode"":""37"",
      ""Sms365"":""37""
   },
   {
      ""Country"":""Mozambique"",
      ""Sim5"":""mozambique"",
      ""getsmscode"":""80"",
      ""Sms365"":""80""
   },
   {
      ""Country"":""Myanmar"",
      ""Sim5"":""myanmar"",
      ""getsmscode"":""5"",
      ""Sms365"":""5""
   },
   {
      ""Country"":""Namibia"",
      ""Sim5"":""namibia"",
      ""getsmscode"":""138"",
      ""Sms365"":""138""
   },
   {
      ""Country"":""Nepal"",
      ""Sim5"":""nepal"",
      ""getsmscode"":""81"",
      ""Sms365"":""81""
   },
   {
      ""Country"":""Netherlands"",
      ""Sim5"":""netherlands"",
      ""getsmscode"":""48"",
      ""Sms365"":""48""
   },
   {
      ""Country"":""New Caledonia"",
      ""Sim5"":""newcaledonia"",
      ""getsmscode"":""185"",
      ""Sms365"":""185""
   },
   {
      ""Country"":""New Zealand"",
      ""Sim5"":""newzealand"",
      ""getsmscode"":""67"",
      ""Sms365"":""67""
   },
   {
      ""Country"":""Nicaragua"",
      ""Sim5"":""nicaragua"",
      ""getsmscode"":""90"",
      ""Sms365"":""90""
   },
   {
      ""Country"":""Niger"",
      ""Sim5"":""niger"",
      ""getsmscode"":""139"",
      ""Sms365"":""139""
   },
   {
      ""Country"":""Nigeria"",
      ""Sim5"":""nigeria"",
      ""getsmscode"":""19"",
      ""Sms365"":""19""
   },
   {
      ""Country"":""North Macedonia"",
      ""Sim5"":""northmacedonia"",
      ""getsmscode"":""183"",
      ""Sms365"":""183""
   },
   {
      ""Country"":""Norway"",
      ""Sim5"":""norway"",
      ""getsmscode"":""174"",
      ""Sms365"":""174""
   },
   {
      ""Country"":""Oman"",
      ""Sim5"":""oman"",
      ""getsmscode"":""107"",
      ""Sms365"":""107""
   },
   {
      ""Country"":""Pakistan"",
      ""Sim5"":""pakistan"",
      ""getsmscode"":""66"",
      ""Sms365"":""66""
   },
   {
      ""Country"":""Panama"",
      ""Sim5"":""panama"",
      ""getsmscode"":""112"",
      ""Sms365"":""112""
   },
   {
      ""Country"":""Papua New Guinea"",
      ""Sim5"":""papuanewguinea"",
      ""getsmscode"":""79"",
      ""Sms365"":""79""
   },
   {
      ""Country"":""Paraguay"",
      ""Sim5"":""paraguay"",
      ""getsmscode"":""87"",
      ""Sms365"":""87""
   },
   {
      ""Country"":""Peru"",
      ""Sim5"":""peru"",
      ""getsmscode"":""65"",
      ""Sms365"":""65""
   },
   {
      ""Country"":""Philippines"",
      ""Sim5"":""philippines"",
      ""getsmscode"":""4"",
      ""Sms365"":""4""
   },
   {
      ""Country"":""Poland"",
      ""Sim5"":""poland"",
      ""getsmscode"":""15"",
      ""Sms365"":""15""
   },
   {
      ""Country"":""Portugal"",
      ""Sim5"":""portugal"",
      ""getsmscode"":""117"",
      ""Sms365"":""117""
   },
   {
      ""Country"":""Puertorico"",
      ""Sim5"":""puertorico"",
      ""getsmscode"":""97"",
      ""Sms365"":""97""
   },
   {
      ""Country"":""Qatar"",
      ""Sim5"":""qatar"",
      ""getsmscode"":""111"",
      ""Sms365"":""111""
   },
   {
      ""Country"":""Reunion"",
      ""Sim5"":""reunion"",
      ""getsmscode"":""146"",
      ""Sms365"":""146""
   },
   {
      ""Country"":""Romania"",
      ""Sim5"":""romania"",
      ""getsmscode"":""32"",
      ""Sms365"":""32""
   },
   {
      ""Country"":""Romania_voice"",
      ""Sim5"":""romania_voice"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Russia"",
      ""Sim5"":""russia"",
      ""getsmscode"":""0"",
      ""Sms365"":""0""
   },
   {
      ""Country"":""Rwanda"",
      ""Sim5"":""rwanda"",
      ""getsmscode"":""140"",
      ""Sms365"":""140""
   },
   {
      ""Country"":""Saint Kitts and Nevis"",
      ""Sim5"":""saintkittsandnevis"",
      ""getsmscode"":""134"",
      ""Sms365"":""134""
   },
   {
      ""Country"":""Saint Lucia"",
      ""Sim5"":""saintlucia"",
      ""getsmscode"":""164"",
      ""Sms365"":""164""
   },
   {
      ""Country"":""Saint Vincent and the Grenadines"",
      ""Sim5"":""saintvincentandgrenadines"",
      ""getsmscode"":""166"",
      ""Sms365"":""166""
   },
   {
      ""Country"":""Salvador"",
      ""Sim5"":""salvador"",
      ""getsmscode"":""101"",
      ""Sms365"":""101""
   },
   {
      ""Country"":""Samoa"",
      ""Sim5"":""samoa"",
      ""getsmscode"":""198"",
      ""Sms365"":""198""
   },
   {
      ""Country"":""Sao Tome and Principe"",
      ""Sim5"":""saotomeandprincipe"",
      ""getsmscode"":""178"",
      ""Sms365"":""178""
   },
   {
      ""Country"":""Saudi Arabia"",
      ""Sim5"":""saudiarabia"",
      ""getsmscode"":""53"",
      ""Sms365"":""53""
   },
   {
      ""Country"":""Senegal"",
      ""Sim5"":""senegal"",
      ""getsmscode"":""61"",
      ""Sms365"":""61""
   },
   {
      ""Country"":""Serbia"",
      ""Sim5"":""serbia"",
      ""getsmscode"":""29"",
      ""Sms365"":""29""
   },
   {
      ""Country"":""Republic of Seychelles"",
      ""Sim5"":""seychelles"",
      ""getsmscode"":""184"",
      ""Sms365"":""184""
   },
   {
      ""Country"":""Sierra Leone"",
      ""Sim5"":""sierraleone"",
      ""getsmscode"":""115"",
      ""Sms365"":""115""
   },
   {
      ""Country"":""Singapore"",
      ""Sim5"":""singapore"",
      ""getsmscode"":""196"",
      ""Sms365"":""196""
   },
   {
      ""Country"":""Slovakia"",
      ""Sim5"":""slovakia"",
      ""getsmscode"":""141"",
      ""Sms365"":""141""
   },
   {
      ""Country"":""Slovenia"",
      ""Sim5"":""slovenia"",
      ""getsmscode"":""59"",
      ""Sms365"":""59""
   },
   {
      ""Country"":""Solomon Islands"",
      ""Sim5"":""solomonislands"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Somalia"",
      ""Sim5"":""somalia"",
      ""getsmscode"":""149"",
      ""Sms365"":""149""
   },
   {
      ""Country"":""South Africa"",
      ""Sim5"":""southafrica"",
      ""getsmscode"":""31"",
      ""Sms365"":""31""
   },
   {
      ""Country"":""South Korea"",
      ""Sim5"":""southkorea"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Southsudan"",
      ""Sim5"":""southsudan"",
      ""getsmscode"":""177"",
      ""Sms365"":""177""
   },
   {
      ""Country"":""Spain"",
      ""Sim5"":""spain"",
      ""getsmscode"":""56"",
      ""Sms365"":""56""
   },
   {
      ""Country"":""Sri Lanka"",
      ""Sim5"":""srilanka"",
      ""getsmscode"":""64"",
      ""Sms365"":""64""
   },
   {
      ""Country"":""Sudan"",
      ""Sim5"":""sudan"",
      ""getsmscode"":""98"",
      ""Sms365"":""98""
   },
   {
      ""Country"":""Suriname"",
      ""Sim5"":""suriname"",
      ""getsmscode"":""142"",
      ""Sms365"":""142""
   },
   {
      ""Country"":""Swaziland"",
      ""Sim5"":""swaziland"",
      ""getsmscode"":""106"",
      ""Sms365"":""106""
   },
   {
      ""Country"":""Sweden"",
      ""Sim5"":""sweden"",
      ""getsmscode"":""46"",
      ""Sms365"":""46""
   },
   {
      ""Country"":""Switzerland"",
      ""Sim5"":""switzerland"",
      ""getsmscode"":""173"",
      ""Sms365"":""173""
   },
   {
      ""Country"":""Syria"",
      ""Sim5"":""syria"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Taiwan"",
      ""Sim5"":""taiwan"",
      ""getsmscode"":""55"",
      ""Sms365"":""55""
   },
   {
      ""Country"":""Tajikistan"",
      ""Sim5"":""tajikistan"",
      ""getsmscode"":""143"",
      ""Sms365"":""143""
   },
   {
      ""Country"":""Tanzania"",
      ""Sim5"":""tanzania"",
      ""getsmscode"":""9"",
      ""Sms365"":""9""
   },
   {
      ""Country"":""Thailand"",
      ""Sim5"":""thailand"",
      ""getsmscode"":""52"",
      ""Sms365"":""52""
   },
   {
      ""Country"":""Trinidad and Tobago"",
      ""Sim5"":""tit"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Togo"",
      ""Sim5"":""togo"",
      ""getsmscode"":""99"",
      ""Sms365"":""99""
   },
   {
      ""Country"":""Tonga"",
      ""Sim5"":""tonga"",
      ""getsmscode"":""197"",
      ""Sms365"":""197""
   },
   {
      ""Country"":""Tunisia"",
      ""Sim5"":""tunisia"",
      ""getsmscode"":""89"",
      ""Sms365"":""89""
   },
   {
      ""Country"":""Turkey"",
      ""Sim5"":""turkey"",
      ""getsmscode"":""62"",
      ""Sms365"":""62""
   },
   {
      ""Country"":""Turkmenistan"",
      ""Sim5"":""turkmenistan"",
      ""getsmscode"":""161"",
      ""Sms365"":""161""
   },
   {
      ""Country"":""Turks and Caicos Island"",
      ""Sim5"":""turksandcaicos"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Uae"",
      ""Sim5"":""uae"",
      ""getsmscode"":""95"",
      ""Sms365"":""95""
   },
   {
      ""Country"":""Uganda"",
      ""Sim5"":""uganda"",
      ""getsmscode"":""75"",
      ""Sms365"":""75""
   },
   {
      ""Country"":""Ukraine"",
      ""Sim5"":""ukraine"",
      ""getsmscode"":""1"",
      ""Sms365"":""1""
   },
   {
      ""Country"":""Uruguay"",
      ""Sim5"":""uruguay"",
      ""getsmscode"":""156"",
      ""Sms365"":""156""
   },
   {
      ""Country"":""USA"",
      ""Sim5"":""usa"",
      ""getsmscode"":""187"",
      ""Sms365"":""187""
   },
   {
      ""Country"":""Uzbekistan"",
      ""Sim5"":""uzbekistan"",
      ""getsmscode"":""40"",
      ""Sms365"":""40""
   },
   {
      ""Country"":""Venezuela"",
      ""Sim5"":""venezuela"",
      ""getsmscode"":""70"",
      ""Sms365"":""70""
   },
   {
      ""Country"":""Vietnam"",
      ""Sim5"":""vietnam"",
      ""getsmscode"":""10"",
      ""Sms365"":""10""
   },
   {
      ""Country"":""British Virgin Islands"",
      ""Sim5"":""virginislands"",
      ""getsmscode"":""null"",
      ""Sms365"":""null""
   },
   {
      ""Country"":""Yemen"",
      ""Sim5"":""yemen"",
      ""getsmscode"":""30"",
      ""Sms365"":""30""
   },
   {
      ""Country"":""Zambia"",
      ""Sim5"":""zambia"",
      ""getsmscode"":""147"",
      ""Sms365"":""147""
   },
   {
      ""Country"":""Zimbabwe"",
      ""Sim5"":""zimbabwe"",
      ""getsmscode"":""96"",
      ""Sms365"":""96""
   }
            // Include the rest of your JSON string here...
        ]";
        public static List<CountryService> GellAllContries()
        {
            List<CountryService> data = JsonConvert.DeserializeObject<List<CountryService>>(Contries);
            return data;
        }
        public static CountryService GetCountry(string contry)
        {
            List<CountryService> data = JsonConvert.DeserializeObject<List<CountryService>>(Contries);
            var result = data.FirstOrDefault(x => x.Country == contry);
            return result;
        }
    }
}
